### ISSUE TITLE
Unable to project

### ISSUE THREAD

**Issue by Reck1501** [RStijn/TrinityCreator#7]
Whenever I attempt to open the project, I get the following error:
"The application which this project type is based on was not found. "
I can't really figure out what I'm missing here.

**Comment by RStijn** [comment]
To install this project read the instructions at
https://github.com/RStijn/TrinityCreator

If you want to modify the project, ensure that you're using Visual Studio
2015 with .NET 4.5.

If you're only getting this error on TrinityCreatorSetup you can either
install WiX 3 or ignore it and set TrinityCreator as startup project.
Op 29-apr.-2016 16:55 schreef "Reck1501" <notifications@github.com>:

Whenever I attempt to open the project, I get the following error:
"The application which this project type is based on was not found. "
I can't really figure out what I'm missing here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/RStijn/TrinityCreator/issues/7>

**Comment by Reck1501** [comment]
Ah, VS 2015. That's the issue then, I'm using VS 2013.
Thanks for the response!
